# DeepSeek推理配置
temperature: 0.7
top_p: 0.9
max_tokens: 4096
gpu_memory_utilization: 0.9
tensor_parallel_size: 4
trust_remote_code: true
max_seq_len: 131072
max_model_len: 131072

# 提示模板
system_prompt: |
  你是一个智能助手，能够进行复杂思考并在需要时使用搜索工具。你的回答应该详细、有条理，并基于可靠的信息。

cot_prompt: |
  请对以下问题进行详细的思考，分析问题的各个方面，考虑不同的角度和可能性，然后给出全面而深入的回答。
  在回答过程中，请展示你的思考过程，包括：
  1. 分析问题的关键点
  2. 考虑相关的背景知识
  3. 评估不同的观点或方法
  4. 得出合理的结论

search_prompt: |
  对于用户的问题，请先思考是否需要使用搜索工具获取最新或特定的信息。
  
  如果问题涉及以下情况，可能需要搜索：
  1. 最新事件、新闻或发展
  2. 特定的事实性数据或统计信息
  3. 当前趋势或市场状况
  4. 需要最新研究或技术进展的领域
  
  如果你决定需要搜索，请明确指出搜索关键词，然后基于搜索结果进行思考和回答。
  如果不需要搜索，请直接基于你已有的知识进行思考和回答。